version: '3'
services:
  app:
    image: ticket-service:1.0
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - STAFF_TOKEN=${STAFF_TOKEN}
      - JWT_KEY=${JWT_KEY}
    ports:
      - "127.0.0.1:8089:8089"
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure

volumes:
  postgres_data: